# Generated by Django 5.2.1 on 2025-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='cupgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='порядок'),
        ),
    ]
