# Generated by Django 5.2.1 on 2025-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_options_cupgroup_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupgroup',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='order_p',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='порядок'),
        ),
    ]
