# Generated by Django 5.2.1 on 2025-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_cupgroup_order_product_order_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group', 'order_p'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='действующая?'),
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.CharField(choices=[('no_alco', 'безалкогольная комната'), ('alco', 'алкогольная комната')], default='no_alco', max_length=10, verbose_name='комната'),
        ),
    ]
