# Generated by Django 5.2.1 on 2025-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_options_product_enabled_product_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='room',
        ),
        migrations.AddField(
            model_name='cupgroup',
            name='room',
            field=models.CharField(choices=[('no_alco', 'безалкогольная комната'), ('alco', 'алкогольная комната')], default='no_alco', max_length=10, verbose_name='комната'),
        ),
    ]
